services:
  nginx:
    image: nginx:1.21-alpine
    container_name: osticket_nginx
    ports:
      - "8081:80" # Using 8081 to avoid conflict with magento1
      - "8443:443" # Using 8443 for SSL
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www
    depends_on:
      - php-fpm
    networks:
      - osticket_network

  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: osticket_php-fpm
    volumes:
      - ./www:/var/www
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - mysql
    networks:
      - osticket_network

  mysql:
    image: mysql:8.0
    container_name: osticket_mysql
    ports:
      - "3307:3306" # Using 3307 to avoid conflict
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - osticket_mysql_data:/var/lib/mysql
    networks:
      osticket_network:
        aliases:
          - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: osticket_phpmyadmin
    links:
      - mysql:db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8082:80" # Using 8082
    networks:
      - osticket_network

volumes:
  osticket_mysql_data:

networks:
  osticket_network:
    driver: bridge
